New-PSDrive -Name "A" -Root "\\SRV-NAS-INFO\Admin Arsenal$" -Persist -PSProvider "FileSystem"
New-PSDrive -Name "B" -Root "\\SRV-NAS-INFO\Users\MJacotet" -Persist -PSProvider "FileSystem"
New-PSDrive -Name "G" -Root "\\Filer\Forum$" -Persist -PSProvider "FileSystem"
New-PSDrive -Name "I" -Root "\\Filer\APPS$" -Persist -PSProvider "FileSystem"
New-PSDrive -Name "J" -Root "\\Filer\ADM$" -Persist -PSProvider "FileSystem"
New-PSDrive -Name "K" -Root "\\Filer\Medical$" -Persist -PSProvider "FileSystem"
New-PSDrive -Name "S" -Root "\\Sccm2012\Sccm_Repository$" -Persist -PSProvider "FileSystem"
New-PSDrive -Name "U" -Root "\\Filer\Users$" -Persist -PSProvider "FileSystem"
New-PSDrive -Name "Y" -Root "\\Srv-nas-info\.ebooks.sympa$" -Persist -PSProvider "FileSystem"
New-PSDrive -Name "V" -Root "\\Srv-Nas-Info\DiskD$" -Persist -PSProvider "FileSystem" 